### ISSUE TITLE
getidle fails due to awk error

### ISSUE THREAD

**Issue by 0x27** [zMarch/Orc#20]
Host is a Debian 8 (Jessie) box. 

awk version 
```
$ awk -W version
mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan

compiled limits:
max NF             32767
sprintf buffer      2040
```

Here is where the bug happens...
```
$ getidle
awk: line 6: function systime never defined
$ 
```

getenum output is as follows:
```
$ getenum
Doing some basic listing of the usual suspects...
Kernel: 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26)
glibc: GNU C Library (Debian GLIBC 2.19-18+deb8u10) stable release version 2.19, by Roland McGrath et al.
Compiled by GNU CC version 4.8.4.
dbus: D-Bus Message Bus Daemon 1.8.22
Init system is: systemd
```

**Comment by zMarch** [comment]
does the command work if you change it to gawk instead of awk?

**Comment by 0x27** [comment]
Apparently the GNU/geniuses who built the Debian 8 minimal install images didn't feel the need to include `gawk`, leaving us with this crippled `mawk` instead. Wonder if there is a workaround for this that won't break compatibility with `gawk`...

**Comment by 0x27** [comment]
Tested it on another box (Ubuntu), and it works fine. They ship with `gawk` instead of this `mawk` nonsense.

**Comment by zMarch** [comment]
i suppose we could always do a version check and depending on the scenario, switch back to my previous monstrosity of awkgrepping

**Comment by UlrichBerntien** [comment]
I use the gawk function systime. In the pull request #23 I have tried to fix it.

**Comment by zMarch** [comment]
Closed! Amazing, guys.
