### ISSUE TITLE
Compatability

### ISSUE THREAD

**Issue by zMarch** [zMarch/Orc#21]
Mostly a note to myself, but upon initializing Orc, it should probably detect what tools are available (ifconfig, curl, a functioning awk, relevant ps flags being available), and construct the various commands in the functions then and there instead of messing around in each function.

an issue here is that if we try and support EVERYTHING, though, orc is going to get pretty unwieldy pretty quickly, so perhaps targeting the most common "weird distro-specific behaviour" is best

**Comment by UlrichBerntien** [comment]
Some thoughts according compatibility from my side:
I see 3 areas to improve the compatibility: **(A)** Documentation **(B)** Implementation **(C)** Testing.

**(A)** The wiki started by David could be fine destination for the documentation.
- A list of operation systems to keep in mind during development would be nice. A whitelist of systems to support. A blacklist of systems which make trouble to support. Debian Server, version >= 8 and Ubuntu Server, version >= 18.04. FreeBSD?
- Supported Shell interpreters could be a second list: Bash, Dash
- I think a self restriction in the used tools could lighten the compatibility. A whitelist: fine to use, and a blacklist: never ust. A graylist: use only after check, if possible code several alternatives. The script could check all tools from the whitelist and show an warning a tool is missing.
- What about [busybox](https://busybox.net/)? This very small environment could be a test case. I am not sure whether the busybox could be support to keep compatibility to a wide system range.

**(B)** The functions could be split into 3 groups:
- compatibility layer: functions containing a switch to different called tools or tools parameter.
- internal functions: functions only used by other functions, not directly by the user
- user functions: functions desired to be used.
All if-then-else constructions to keep compatibility should be located inside functions in the compatibility layer.

**(C)** The testing could become very fast a big challenge.
- The static code analyze by [ShellCheck](https://www.shellcheck.net/) could be helpful.
- Test automatisation would be very helpful. In the moment I don't see a good start point for creating some automatic test.

**Comment by 0x27** [comment]
Re: C, test automation - I also can't think of a good way to automate functionality testing, and suspect that would have to be done by hand.

I could start off, I guess, by working on writing a "testing document" outlining how to test all the functions (what the prerequisites are, how to validate, expected output)? 

Also shouldn't be too hard to spin up an instance of ShellCheck on a cheap VPS somewhere and have it do its thing!

**Comment by UlrichBerntien** [comment]
Re: ShellCheck on a cheap VPS
[Travis](https://travis-ci.org/) CI run it for free. I tried it on my fork in the [shellcheck-02](https://github.com/UlrichBerntien/Orc/tree/shellcheck-02) branch.
To include the service a sign-in and an activation is needed for [Travis](https://travis-ci.org/).

**Comment by zMarch** [comment]
I think we've cleared up as many shellcheck findings as possible - later I'll tweak our travis setup so that it doesn't yell at us for things that are necessary! Closed, for now.
