### ISSUE TITLE
Fix bug in hangup

### ISSUE THREAD

**Issue by 0x27** [zMarch/Orc#28]
I accidentally introduced a bug in the `hangup` function. If you run it without arguments, it kills everyone elses session on the box. 

This is great and all, but not exactly what I intended to do. 

I should probably rewrite this function to work better.

**Comment by 0x27** [comment]
Example:

```
$ getidle
PTY 0 is 25621 seconds idle and owned by user1
PTY 1 is 0 seconds idle and owned by root ** this is us **
PTY 2 is 663 seconds idle and owned by user2
PTY 4 is 15657 seconds idle and owned by user3
$ hangup
This is seriously rude...
Terminating PTS/
Owner of PTS is root
SSH PID is 24893
36610
42622
sh: 433: cannot create /dev/pts/: Is a directory
$ 
```

In this case I was not in over SSH, but over another PTY spawning backdoor - this also begs the question of why I am only targeting SSH connections - there are times when we might want to kill a user who is accessing via telnet or another remote access tool which allocates a PTY, for example.

**Comment by zMarch** [comment]
MESS WITH THE BEST
i'll have a look when i'm home and throw in some handling to stop it killing every single session

**Comment by UlrichBerntien** [comment]
I have added some checks in the hangup function in the pull request #30.
Please test it.
I will try to add argument 'all' for all sshd clients and a list of PTS numbers.

**Comment by UlrichBerntien** [comment]
In pull request #31 special arguments were added:
"hangup all" to terminate all and "hangup all other" to terminate all by not our PTS is now supported.

**Comment by 0x27** [comment]
Appears to work fine on Debian/Ubuntu hosts I've been testing on. I'll probably have to add CentOS and such to my set of VM's though going forward as per your notes in https://github.com/zMarch/Orc/issues/21
