### ISSUE TITLE
Wiki editing and adding docs

### ISSUE THREAD

**Issue by 0x27** [zMarch/Orc#29]
Have created a wiki, gotta start documenting stuff... https://github.com/zMarch/Orc/wiki

**Comment by zMarch** [comment]
What do we think about an IRC channel?

**Comment by 0x27** [comment]
Very positively. Would allow for more streamlined real time discussion than just posting in issues.

**Comment by zMarch** [comment]
#orc now lives in irc.hackint.eu!

**Comment by zMarch** [comment]
I think this can be closed, currently! We've got wiki etc.
