### ISSUE TITLE
Choosing a license

### ISSUE THREAD

**Issue by UlrichBerntien** [zMarch/Orc#36]
I would suggest to add a license to the repository. Choosing and attaching a license file is just a few steps. [Add license file](https://github.com/zMarch/Orc/community/license/new?branch=master)
In my opinion, the MIT license or the Apache license could be used. ([Overview](https://choosealicense.com/appendix/))

**Comment by zMarch** [comment]
I've been thinking about this recently - my preference would likely be the MIT license, myself.
