### ISSUE TITLE
Shellcheck...

### ISSUE THREAD

**Issue by zMarch** [zMarch/Orc#52]
I've essentially ignored some directives for now, mostly ones that seemed a bit janky (erroring on ulimit when it was in an if) or were purely informational. We now pass. It's not cheating!

**Comment by UlrichBerntien** [comment]
To pass shellcheck is a fine step. Now the shellcheck pass state could be hold at each change.

I also see ignore directives as a normal part of using automatic checks. The check programs will never cover all situations. The checks gives hints and  a comment like "I read the hint, understand the hint, and decided it is ok to ignore the hin" is realy not cheating.

A second step could be to integrate some test, simple shell script file calling some functions of Orc or more sophisticated with [kward/shunit2](https://github.com/kward/shunit2) or [bats-core/bats-core
](https://github.com/bats-core/bats-core) in the Travis CI build step.

But next I will focus me on the getnet rework.
