### ISSUE TITLE
Add x86 memexec using memfd

### ISSUE THREAD

**Issue by 0x27** [zMarch/Orc#6]
Going to rename memexec and add the x86 version once I have it tested fully and can confirm it works. Then we will have memfdexec32 and memfdexec64. 

We COULD have architecture detection and selection of the method in the perl blob and merge them back into one command, but that is a later problem to solve IMO.

Might want to consider implementing the shm-exec method implemented as a fallback in [netelf](https://github.com/xiphosresearch/netelf/) for boxes with too-old kernels, but that is a separate problem.

**Comment by UlrichBerntien** [comment]
Now the memexec function in the pull request #61 should include the desired options.
- The Perl script blob should detect i386, x86_64 and some other architectures.
- As fallback if Perl is not available a Python script blob should work in the same way.
- As fallback if the Linux is too old (< 3.17) the shell script should load the file into $HOME.

**Comment by UlrichBerntien** [comment]
memexec with i386 and x86 support is implemented.
