### ISSUE TITLE
find setuid/setcap bins?

### ISSUE THREAD

**Issue by darrenmartyn** [zMarch/Orc#65]
Wondering if there is any value in adding some functionality to find setuid files? Basically just a function that calls `find / -perm 4000 2>/dev/null` (for setuid) and `getcap -r / 2>/dev/null` (for setcap) and maybe does some output parsing or further processing? I'm unsure what "further processing" would actually be useful, but checking these binaries for RPATH issues or against the [gtfobins](https://gtfobins.github.io) list and such is sometimes fruitful.

**Comment by UlrichBerntien** [comment]
New function getsfiles is merged into the master branch.
See pull #67

**Comment by UlrichBerntien** [comment]
Function is implemented: [getsfiles](https://github.com/zMarch/Orc/wiki/getsfiles).
No additional comments in one Week.
→ close
