### ISSUE TITLE
Use "ip a" instead of "ifconfig"

### ISSUE THREAD

**Issue by q2dg** [zMarch/Orc#77]
net-tools package (where ifconfig, netstat, route...commands belong) is deprecated and not installed by default in increasingly more distributions.
Thanks

**Comment by UlrichBerntien** [comment]
I think Orc should support old and new systems.

Inside the Orc file is the section "Compatibility Layer". The functions in this layer should check which program (ip or ifconfig) exists, then calling the existing program. Function "orc_existsProg" does the check.

See for example the orc_listBroadcastAddress function. If ip exists, then the ip command is used else the old ifconfig is used.

Checking the usage of ifconfig during writing this message I found a bug in line 948. I will fixed the bug soon. All other usages of ifconfig should be inside a check.

If you found another usage of ifconfig without a check before, please report the bug,

**Comment by q2dg** [comment]
Ok.
Thanks for your so clear explanation.
I'll close the issue, then.
Thanks!
